### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by jhermsmeier** [ShieldBattery/node-interval-tree#11]
Hey! Wanted to ask if you would be interested in adding support for `BigInt`s in intervals?
I have a scrappy branch at hand where I explored it, and would be happy to polish it up & send a pull request :)

**Comment by 2Pacalypse-** [comment]
Hey, I'm not opposed to having support for `BigInt`s in particular, but this would have to be an opt-in feature so we don't force everyone that they have to use `BigInt`s as I imagine that's a reasonably rare use case. I'm not sure what's the best way to achieve that though ^^

**Comment by 2Pacalypse-** [comment]
Done in 52458af1f571748f58d87e4242670cd1063d5673. Thx @jhermsmeier!
