### ISSUE TITLE
Doesn't return any value in angular2

### ISSUE THREAD

**Issue by ghost** [ShieldBattery/node-interval-tree#2]
Hi guys !

I'm trying to use your algorithm in angular 2 but it doesn't seem to work.

Here is my code :
```javascript
this.intervalTree = new IntervalTree();
this.intervalTree.insert(0, 5, "foo");
console.log(this.intervalTree.search(2, 8));
console.log(this.intervalTree);
```
And how I import it in angular 2 : import {IntervalTree} from 'node-interval-tree';

I used npm to install it and I don't have any error running the code. The array returned by the search is just empty.

Any clues ?

Best regards,
Waylander.

**Comment by 2Pacalypse-** [comment]
Hi!

You're using the [advanced usage](https://github.com/ShieldBattery/node-interval-tree#advanced-usage) way to import the interval tree.

To use it so it works with your example code, you should use the default export, ie. import it like this:
```javascript
import IntervalTree from 'node-interval-tree'
```

**Comment by ghost** [comment]
Thank you very much its working ! :+1:

**Comment by 2Pacalypse-** [comment]
👍
