### ISSUE TITLE
Persistence in database

### ISSUE THREAD

**Issue by dnmd** [ShieldBattery/node-interval-tree#7]
Thanks for sharing this awesome lib! I do have a question though, what approach would you recommend / take when it comes to persisting an `IntervalTree` / interval tree like structure in a NoSQL database?

Querying is limited in NoSQL, and it is often recommended to rethink the data structure instead. So when I was looking for alternatives to “query” for overlapping ranges I stumbled upon this interval tree technique, and it got me wondering…

Maybe I misinterpreted things regarding the interval tree, and does this technique not lend itself to be applied on actual databases structures… don’t hesitate to enlighten me ;)

**Comment by 2Pacalypse-** [comment]
Sure, you could probably implement this data structure on a database layer. There are various [hierarchical database models](https://en.wikipedia.org/wiki/Hierarchical_database_model) that you could use (of course, you'd probably have to extend the models to work with interval data). However, it'd be quite a bit of work to do. You'd have to reimplement pretty much this whole library through SQL queries, which would be a nightmare. And the performance would be questionable as well.

I'm struggling to see why you'd want to do that though. Database should be for storing data, which you can then use to create the interval tree in memory when your application is running. If you're worrying your data is too big or you have too much of it, you could optimize it a bit to only store `id`s of the data or something in the interval tree. Then, once you have the overlapping intervals that you've searched for, you can fetch the actual data from the database by their `id`s.
