### ISSUE TITLE
Possible to search for "nearest interval" on a miss?

### ISSUE THREAD

**Issue by mpolichette** [ShieldBattery/node-interval-tree#9]
I'm wondering there is an easy way to search for the nearest interval left/right if you search by a point and it does not overlap w/ any intervals.

Would that be a good candidate for this library or not really?

**Comment by 2Pacalypse-** [comment]
This library is using a specific data structure [(AVL tree](https://en.wikipedia.org/wiki/AVL_tree)) and augments it to implement a solution to a specific problem, namely range searches through [interval trees](https://en.wikipedia.org/wiki/Interval_tree).

What you're asking about is called the [nearest neighbor search](https://en.wikipedia.org/wiki/Nearest_neighbor_search), and it would require a different solution altogether. For example, a [k-d tree](https://en.wikipedia.org/wiki/K-d_tree) could probably be used to solve both problems at once (range searches + nearest neighbor search), but I have no plans in rewriting this library to use a k-d tree.

That problem would better be solved as a different library. This library does one thing and does it well (I hope). If you really needed something that works right now, you *could* use this library to search for a specific range, then if you don't get any results, you can expand your range and search again. However, that is probably not an ideal way to go about solving your problem.

**Comment by mpolichette** [comment]
Cool, I'll explore those! Thanks for the informative response @2Pacalypse- I appreciate it!
